import type { CrudModuleConfig, FieldDef, StatusMeta } from '@/components/shared/crud-page';
import { demoRows } from '@/lib/modules/demo-rows';

const companyOptions = [
  { value: 'arya', label: 'آزیا آریا لمتید|Azya Aria LTD' },
  { value: 'turkmen', label: 'ترکمن پطرولیم|Turkmen Petroleum Company' },
];

const docStatus: Record<string, StatusMeta> = {
  draft: { label: 'پیش‌نویس|Draft', variant: 'muted' },
  pending: { label: 'در انتظار|Pending', variant: 'warning' },
  approved: { label: 'تأیید شده|Approved', variant: 'success' },
  completed: { label: 'تکمیل|Completed', variant: 'success' },
  cancelled: { label: 'لغو|Cancelled', variant: 'danger' },
  open: { label: 'باز|Open', variant: 'info' },
  paid: { label: 'پرداخت‌شده|Paid', variant: 'success' },
  partial: { label: 'جزئی|Partial', variant: 'warning' },
  overdue: { label: 'سررسید گذشته|Overdue', variant: 'danger' },
  delivered: { label: 'تحویل‌شده|Delivered', variant: 'success' },
  in_transit: { label: 'در مسیر|In transit', variant: 'info' },
  active: { label: 'فعال|Active', variant: 'success' },
  inactive: { label: 'غیرفعال|Inactive', variant: 'muted' },
  cleared: { label: 'ترخیص‌شده|Cleared', variant: 'success' },
  holding: { label: 'نگهداری|Holding', variant: 'warning' },
  archived: { label: 'آرشیو|Archived', variant: 'muted' },
};

function companyField(list = true): FieldDef {
  return {
    key: 'company',
    label: 'شرکت|Company',
    type: 'select',
    options: companyOptions,
    required: true,
    list,
  };
}

function statusField(options?: { value: string; label: string }[]): FieldDef {
  return {
    key: 'status',
    label: 'وضعیت|Status',
    type: 'select',
    options: options ?? [
      { value: 'draft', label: 'پیش‌نویس|Draft' },
      { value: 'pending', label: 'در انتظار|Pending' },
      { value: 'approved', label: 'تأیید شده|Approved' },
      { value: 'completed', label: 'تکمیل|Completed' },
      { value: 'cancelled', label: 'لغو|Cancelled' },
    ],
    required: true,
    list: true,
  };
}

function notesField(): FieldDef {
  return {
    key: 'notes',
    label: 'ملاحظات|Notes',
    type: 'textarea',
    list: false,
    search: true,
  };
}

export const modules = {
  purchaseOrders: {
    title: 'درخواست خرید|Purchase requests',
    description: 'مدیریت درخواست‌های خرید قبل از بل و ورود کالا',
    entityName: 'درخواست خرید|Purchase requests',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره درخواست', required: true, list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'supplier', label: 'تأمین‌کننده|Vendor', required: true, list: true, search: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار (تن)', type: 'number' as const, required: true, list: true },
      { key: 'unitPrice', label: 'قیمت واحد', type: 'number' as const, money: true, list: true },
      { key: 'amount', label: 'مبلغ کل', type: 'number' as const, money: true, list: true },
      { key: 'currency', label: 'ارز|Currency', type: 'select' as const, options: [
        { value: 'USD', label: 'USD' }, { value: 'AED', label: 'AED' }, { value: 'AFN', label: 'AFN' },
      ], list: true },
      companyField(),
      statusField(),
      notesField(),
    ],
    initialRows: demoRows.purchaseOrders,
  },

  purchaseInvoices: {
    title: 'بل خرید|Purchase bills',
    description: 'ثبت و پیگیری بل‌های خرید از تأمین‌کنندگان',
    entityName: 'بل خرید|Purchase bills',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره بل', required: true, list: true, search: true },
      { key: 'poCode', label: 'درخواست مرتبط', list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'supplier', label: 'تأمین‌کننده|Vendor', required: true, list: true, search: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار|Quantity', type: 'number' as const, list: true },
      { key: 'amount', label: 'مبلغ|Amount', type: 'number' as const, money: true, list: true },
      { key: 'paid', label: 'پرداخت‌شده|Paid', type: 'number' as const, money: true, list: true },
      { key: 'balance', label: 'مانده', type: 'number' as const, money: true, list: true },
      { key: 'dueDate', label: 'سررسید', type: 'date' as const, list: true },
      { key: 'currency', label: 'ارز|Currency', type: 'select' as const, options: [
        { value: 'USD', label: 'USD' }, { value: 'AED', label: 'AED' }, { value: 'AFN', label: 'AFN' },
      ], list: true },
      { key: 'warehouse', label: 'گدام', list: true },
      companyField(),
      statusField([
        { value: 'pending', label: 'در انتظار|Pending' },
        { value: 'partial', label: 'جزئی|Partial' },
        { value: 'paid', label: 'پرداخت‌شده|Paid' },
        { value: 'overdue', label: 'سررسید گذشته|Overdue' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.purchaseInvoices,
  },

  purchaseReturns: {
    title: 'برگشت خرید|Purchase returns',
    description: 'ثبت برگشت کالا به تأمین‌کننده و اصلاح حساب',
    entityName: 'برگشت خرید|Purchase returns',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره برگشت', required: true, list: true, search: true },
      { key: 'invoiceCode', label: 'بل', list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'supplier', label: 'تأمین‌کننده|Vendor', required: true, list: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار برگشتی', type: 'number' as const, list: true },
      { key: 'amount', label: 'مبلغ|Amount', type: 'number' as const, money: true, list: true },
      { key: 'reason', label: 'علت', required: true, list: true, search: true },
      companyField(),
      statusField(),
      notesField(),
    ],
    initialRows: demoRows.purchaseReturns,
  },

  salesOrders: {
    title: 'درخواست فروش|Sales requests',
    description: 'درخواست‌های فروش مشتریان قبل از بل و بارگیری',
    entityName: 'درخواست فروش|Sales requests',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره درخواست', required: true, list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'customer', label: 'مشتری|Customer', required: true, list: true, search: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار|Quantity', type: 'number' as const, list: true },
      { key: 'unitPrice', label: 'قیمت واحد', type: 'number' as const, money: true, list: true },
      { key: 'amount', label: 'مبلغ|Amount', type: 'number' as const, money: true, list: true },
      { key: 'warehouse', label: 'گدام', list: true },
      companyField(),
      statusField(),
      notesField(),
    ],
    initialRows: demoRows.salesOrders,
  },

  salesInvoices: {
    title: 'بل فروش|Sales bills',
    description: 'صدور و پیگیری بل‌های فروش',
    entityName: 'بل فروش|Sales bills',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره بل', required: true, list: true, search: true },
      { key: 'soCode', label: 'درخواست', list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'customer', label: 'مشتری|Customer', required: true, list: true, search: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار|Quantity', type: 'number' as const, list: true },
      { key: 'amount', label: 'مبلغ|Amount', type: 'number' as const, money: true, list: true },
      { key: 'received', label: 'دریافت‌شده', type: 'number' as const, money: true, list: true },
      { key: 'balance', label: 'مانده', type: 'number' as const, money: true, list: true },
      { key: 'dueDate', label: 'سررسید', type: 'date' as const, list: true },
      { key: 'currency', label: 'ارز|Currency', type: 'select' as const, options: [
        { value: 'USD', label: 'USD' }, { value: 'AED', label: 'AED' }, { value: 'AFN', label: 'AFN' },
      ], list: true },
      { key: 'warehouse', label: 'گدام', list: true },
      companyField(),
      statusField([
        { value: 'pending', label: 'در انتظار|Pending' },
        { value: 'partial', label: 'جزئی|Partial' },
        { value: 'paid', label: 'تسویه‌شده' },
        { value: 'overdue', label: 'سررسید گذشته|Overdue' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.salesInvoices,
  },

  salesDeliveries: {
    title: 'بارگیری / حواله خروج',
    description: 'ثبت بارگیری و حواله خروج از گدام',
    entityName: 'حواله خروج|Delivery note',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره حواله', required: true, list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'customer', label: 'مشتری|Customer', required: true, list: true, search: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار|Quantity', type: 'number' as const, list: true },
      { key: 'warehouse', label: 'گدام مبدأ', list: true },
      { key: 'vehicle', label: 'وسیله نقلیه', list: true, search: true },
      { key: 'driver', label: 'راننده|Driver', list: true },
      companyField(),
      statusField([
        { value: 'pending', label: 'در انتظار|Pending' },
        { value: 'in_transit', label: 'در مسیر|In transit' },
        { value: 'delivered', label: 'تحویل‌شده|Delivered' },
        { value: 'cancelled', label: 'لغو|Cancelled' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.salesDeliveries,
  },

  salesReturns: {
    title: 'برگشت فروش|Sales returns',
    description: 'ثبت برگشت کالای فروخته‌شده از مشتری',
    entityName: 'برگشت فروش|Sales returns',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره برگشت', required: true, list: true, search: true },
      { key: 'invoiceCode', label: 'بل', list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'customer', label: 'مشتری|Customer', required: true, list: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار|Quantity', type: 'number' as const, list: true },
      { key: 'amount', label: 'مبلغ|Amount', type: 'number' as const, money: true, list: true },
      { key: 'reason', label: 'علت', required: true, list: true },
      companyField(),
      statusField(),
      notesField(),
    ],
    initialRows: demoRows.salesReturns,
  },

  warehouseTransfers: {
    title: 'انتقال بین گدام‌ها',
    description: 'جابه‌جایی موجودی بین انبارها و مخازن',
    entityName: 'انتقال|Transfer',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره سند', required: true, list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'fromWarehouse', label: 'از گدام', required: true, list: true },
      { key: 'toWarehouse', label: 'به گدام', required: true, list: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار|Quantity', type: 'number' as const, list: true },
      { key: 'vehicle', label: 'وسیله', list: true },
      companyField(),
      statusField(),
      notesField(),
    ],
    initialRows: demoRows.warehouseTransfers,
  },

  tanks: {
    title: 'مخازن و تانک‌ها',
    description: 'ظرفیت، موجودی و وضعیت مخازن سوخت',
    entityName: 'مخزن|Tank',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد مخزن', required: true, list: true, search: true },
      { key: 'name', label: 'نام|Name', required: true, list: true, search: true },
      { key: 'warehouse', label: 'گدام', required: true, list: true },
      { key: 'product', label: 'کالای اختصاصی', required: true, list: true },
      { key: 'capacity', label: 'ظرفیت', type: 'number' as const, list: true },
      { key: 'capacityUnit', label: 'واحد ظرفیت', list: true },
      { key: 'port', label: 'بندر', list: true },
      { key: 'currentQty', label: 'موجودی فعلی', type: 'number' as const, list: true },
      { key: 'reserved', label: 'رزرو', type: 'number' as const, list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'holding', label: 'نگهداری|Holding' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.tanks,
  },

  stocktakes: {
    title: 'انبارگردانی|Stocktake',
    description: 'شمارش فیزیکی و مغایرت‌گیری موجودی',
    entityName: 'انبارگردانی|Stocktake',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره', required: true, list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'warehouse', label: 'گدام', required: true, list: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'systemQty', label: 'موجودی سیستم', type: 'number' as const, list: true },
      { key: 'countedQty', label: 'شمارش فیزیکی', type: 'number' as const, list: true },
      { key: 'diff', label: 'مغایرت', type: 'number' as const, list: true },
      { key: 'countedBy', label: 'شمارش‌گر', list: true },
      companyField(),
      statusField(),
      notesField(),
    ],
    initialRows: demoRows.stocktakes,
  },

  transit: {
    title: 'ترانزیت|Transit',
    description: 'پیگیری محموله‌های ترانزیتی در مسیر',
    entityName: 'ترانزیت|Transit',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره ترانزیت', required: true, list: true, search: true },
      { key: 'date', label: 'تاریخ حرکت', type: 'date' as const, required: true, list: true },
      { key: 'origin', label: 'مبدأ', required: true, list: true },
      { key: 'destination', label: 'مقصد', required: true, list: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار|Quantity', type: 'number' as const, list: true },
      { key: 'carrier', label: 'حمل‌کننده', list: true, search: true },
      { key: 'border', label: 'مرز', list: true },
      companyField(),
      statusField([
        { value: 'pending', label: 'در انتظار|Pending' },
        { value: 'in_transit', label: 'در مسیر|In transit' },
        { value: 'cleared', label: 'ترخیص‌شده|Cleared' },
        { value: 'completed', label: 'تکمیل|Completed' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.transit,
  },

  wagons: {
    title: 'واگن‌ها',
    description: 'ثبت و پیگیری واگن‌های ریلی',
    entityName: 'واگن|Wagon',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره واگن', required: true, list: true, search: true },
      { key: 'type', label: 'نوع', list: true },
      { key: 'capacity', label: 'ظرفیت', type: 'number' as const, list: true },
      { key: 'capacityUnit', label: 'واحد ظرفیت', list: true },
      { key: 'port', label: 'بندر', list: true },
      { key: 'product', label: 'محموله فعلی', list: true },
      { key: 'qty', label: 'مقدار|Quantity', type: 'number' as const, list: true },
      { key: 'location', label: 'موقعیت', list: true, search: true },
      { key: 'owner', label: 'مالک', list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'in_transit', label: 'در مسیر|In transit' },
        { value: 'holding', label: 'متوقف' },
        { value: 'inactive', label: 'خارج از سرویس' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.wagons,
  },

  trucks: {
    title: 'موترها',
    description: 'ناوگان جاده‌ای و وضعیت بهره‌برداری',
    entityName: 'موتر|Truck',
    statusMap: docStatus,
    fields: [
      { key: 'plate', label: 'پلاک', required: true, list: true, search: true },
      { key: 'model', label: 'مدل', list: true, search: true },
      { key: 'capacity', label: 'ظرفیت', type: 'number' as const, list: true },
      { key: 'capacityUnit', label: 'واحد ظرفیت', list: true },
      { key: 'port', label: 'بندر', list: true },
      { key: 'driver', label: 'راننده|Driver', list: true, search: true },
      { key: 'transportCompany', label: 'شرکت حمل|Carrier', list: true },
      { key: 'currentLoad', label: 'بار فعلی', list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'آماده' },
        { value: 'in_transit', label: 'در مسیر|In transit' },
        { value: 'holding', label: 'تعمیر' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.trucks,
  },

  drivers: {
    title: 'رانندگان',
    description: 'اطلاعات رانندگان و مدارک',
    entityName: 'راننده|Driver',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد|Code', required: true, list: true, search: true },
      { key: 'name', label: 'نام|Name', required: true, list: true, search: true },
      { key: 'phone', label: 'تلفن|Phone', required: true, list: true, search: true },
      { key: 'licenseNo', label: 'شماره گواهینامه', list: true },
      { key: 'licenseExpiry', label: 'انقضای گواهینامه', type: 'date' as const, list: true },
      { key: 'vehicle', label: 'موتر فعلی', list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'holding', label: 'مرخصی' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.drivers,
  },

  transportCompanies: {
    title: 'شرکت‌های حمل',
    description: 'پیمانکاران حمل جاده‌ای و ریلی',
    entityName: 'شرکت حمل|Carrier',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد|Code', required: true, list: true, search: true },
      { key: 'name', label: 'نام شرکت', required: true, list: true, search: true },
      { key: 'phone', label: 'تلفن|Phone', list: true },
      { key: 'contactPerson', label: 'شخص تماس', list: true },
      { key: 'vehiclesCount', label: 'تعداد ناوگان', type: 'number' as const, list: true },
      { key: 'ratePerTon', label: 'نرخ هر تن', type: 'number' as const, money: true, list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.transportCompanies,
  },

  customs: {
    title: 'گمرک',
    description: 'ترخیص، اظهارنامه و هزینه‌های گمرکی',
    entityName: 'پرونده گمرک|Customs case',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره پرونده', required: true, list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'border', label: 'مرز / گمرک', required: true, list: true },
      { key: 'declarationNo', label: 'شماره اظهارنامه', list: true, search: true },
      { key: 'product', label: 'کالا|Product', required: true, list: true },
      { key: 'qty', label: 'مقدار|Quantity', type: 'number' as const, list: true },
      { key: 'dutyAmount', label: 'عوارض', type: 'number' as const, money: true, list: true },
      companyField(),
      statusField([
        { value: 'pending', label: 'در جریان' },
        { value: 'holding', label: 'نگهداری|Holding' },
        { value: 'cleared', label: 'ترخیص‌شده|Cleared' },
        { value: 'cancelled', label: 'لغو|Cancelled' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.customs,
  },

  receivables: {
    title: 'حسابات دریافتنی',
    description: 'بدهی مشتریان و پیگیری وصول مطالبات',
    entityName: 'طلب|Receivable',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد|Code', required: true, list: true, search: true },
      { key: 'customer', label: 'مشتری|Customer', required: true, list: true, search: true },
      { key: 'invoiceCode', label: 'بل', list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, list: true },
      { key: 'dueDate', label: 'سررسید', type: 'date' as const, list: true },
      { key: 'amount', label: 'مبلغ|Amount', type: 'number' as const, money: true, list: true },
      { key: 'received', label: 'وصول‌شده', type: 'number' as const, money: true, list: true },
      { key: 'balance', label: 'مانده', type: 'number' as const, money: true, list: true },
      companyField(),
      statusField([
        { value: 'open', label: 'باز|Open' },
        { value: 'partial', label: 'جزئی|Partial' },
        { value: 'paid', label: 'تسویه' },
        { value: 'overdue', label: 'سررسید گذشته|Overdue' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.receivables,
  },

  payables: {
    title: 'حسابات پرداختنی',
    description: 'بدهی به تأمین‌کنندگان و زمان‌بندی پرداخت',
    entityName: 'بدهی|Payable',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد|Code', required: true, list: true, search: true },
      { key: 'supplier', label: 'تأمین‌کننده|Vendor', required: true, list: true, search: true },
      { key: 'invoiceCode', label: 'بل', list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, list: true },
      { key: 'dueDate', label: 'سررسید', type: 'date' as const, list: true },
      { key: 'amount', label: 'مبلغ|Amount', type: 'number' as const, money: true, list: true },
      { key: 'paid', label: 'پرداخت‌شده|Paid', type: 'number' as const, money: true, list: true },
      { key: 'balance', label: 'مانده', type: 'number' as const, money: true, list: true },
      companyField(),
      statusField([
        { value: 'open', label: 'باز|Open' },
        { value: 'partial', label: 'جزئی|Partial' },
        { value: 'paid', label: 'پرداخت‌شده|Paid' },
        { value: 'overdue', label: 'سررسید گذشته|Overdue' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.payables,
  },

  banks: {
    title: 'بانک‌ها',
    description: 'حساب‌های بانکی و موجودی',
    entityName: 'حساب بانکی|Bank account',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد حساب', required: true, list: true, search: true },
      { key: 'bankName', label: 'نام بانک', required: true, list: true, search: true },
      { key: 'accountNo', label: 'شماره حساب', required: true, list: true, search: true },
      { key: 'currency', label: 'ارز|Currency', type: 'select' as const, options: [
        { value: 'USD', label: 'USD' }, { value: 'AFN', label: 'AFN' }, { value: 'AED', label: 'AED' },
      ], list: true },
      { key: 'balance', label: 'موجودی', type: 'number' as const, money: true, list: true },
      { key: 'branch', label: 'شعبه بانک', list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.banks,
  },

  cashAccounts: {
    title: 'صندوق و خزانه',
    description: 'موجودی نقدی صندوق‌ها و خزانه‌ها',
    entityName: 'صندوق|Cash box',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد|Code', required: true, list: true, search: true },
      { key: 'name', label: 'نام صندوق', required: true, list: true, search: true },
      { key: 'cashier', label: 'صندوق‌دار', list: true },
      { key: 'currency', label: 'ارز|Currency', type: 'select' as const, options: [
        { value: 'USD', label: 'USD' }, { value: 'AFN', label: 'AFN' },
      ], list: true },
      { key: 'balance', label: 'موجودی', type: 'number' as const, money: true, list: true },
      { key: 'location', label: 'محل', list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.cashAccounts,
  },

  ledgerAccounts: {
    title: 'دفتر کل',
    description: 'سرفصل‌های حسابداری و مانده‌ها',
    entityName: 'حساب|Account',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد حساب', required: true, list: true, search: true },
      { key: 'name', label: 'نام حساب', required: true, list: true, search: true },
      { key: 'type', label: 'نوع', type: 'select' as const, options: [
        { value: 'asset', label: 'دارایی' },
        { value: 'liability', label: 'بدهی|Payable' },
        { value: 'equity', label: 'حقوق صاحبان' },
        { value: 'income', label: 'درآمد' },
        { value: 'expense', label: 'هزینه' },
      ], list: true },
      { key: 'debit', label: 'بدهکار', type: 'number' as const, money: true, list: true },
      { key: 'credit', label: 'بستانکار', type: 'number' as const, money: true, list: true },
      { key: 'balance', label: 'مانده', type: 'number' as const, money: true, list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'بسته' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.ledgerAccounts,
  },

  journalVouchers: {
    title: 'سند حسابداری',
    description: 'ثبت اسناد حسابداری دوطرفه',
    entityName: 'سند|Voucher',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره سند', required: true, list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'description', label: 'شرح', required: true, list: true, search: true },
      { key: 'debitAccount', label: 'حساب بدهکار', required: true, list: true },
      { key: 'creditAccount', label: 'حساب بستانکار', required: true, list: true },
      { key: 'amount', label: 'مبلغ|Amount', type: 'number' as const, money: true, list: true },
      { key: 'refDoc', label: 'سند مرجع', list: true, search: true },
      companyField(),
      statusField(),
      notesField(),
    ],
    initialRows: demoRows.journalVouchers,
  },

  expenses: {
    title: 'مصارف',
    description: 'ثبت هزینه‌های عملیاتی و اداری',
    entityName: 'مصرف|Expense',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره', required: true, list: true, search: true },
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true },
      { key: 'category', label: 'دسته', type: 'select' as const, options: [
        { value: 'transport', label: 'حمل' },
        { value: 'customs', label: 'گمرک' },
        { value: 'salary', label: 'معاش' },
        { value: 'office', label: 'اداری' },
        { value: 'other', label: 'سایر' },
      ], list: true },
      { key: 'title', label: 'عنوان', required: true, list: true, search: true },
      { key: 'amount', label: 'مبلغ|Amount', type: 'number' as const, money: true, list: true },
      { key: 'paidFrom', label: 'از محل', list: true },
      companyField(),
      statusField(),
      notesField(),
    ],
    initialRows: demoRows.expenses,
  },

  currencies: {
    title: 'مدیریت ارز',
    description: 'ارزهای فعال سیستم',
    entityName: 'ارز|Currency',
    statusMap: docStatus,
    showCompanySwitcher: false,
    fields: [
      { key: 'code', label: 'کد|Code', required: true, list: true, search: true },
      { key: 'name', label: 'نام|Name', required: true, list: true, search: true },
      { key: 'nameLocal', label: 'نام محلی', list: true },
      { key: 'symbol', label: 'نماد', list: true },
      { key: 'decimalPlaces', label: 'اعشار', type: 'number' as const, list: true },
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.currencies,
  },

  fxRates: {
    title: 'نرخ ارز|FX rate',
    description: 'نرخ‌های تبدیل روزانه',
    entityName: 'نرخ ارز|FX rate',
    statusMap: docStatus,
    showCompanySwitcher: false,
    fields: [
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true, search: true },
      { key: 'baseCurrency', label: 'ارز مبدأ', required: true, list: true },
      { key: 'quoteCurrency', label: 'ارز مقصد', required: true, list: true },
      { key: 'buyRate', label: 'نرخ خرید', type: 'number' as const, list: true },
      { key: 'sellRate', label: 'نرخ فروش', type: 'number' as const, list: true },
      { key: 'source', label: 'منبع', list: true },
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'آرشیو|Archived' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.fxRates,
  },

  employees: {
    title: 'کارمندان',
    description: 'پرسنل و اطلاعات استخدامی',
    entityName: 'کارمند|Employee',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد پرسنلی', required: true, list: true, search: true },
      { key: 'name', label: 'نام|Name', required: true, list: true, search: true },
      { key: 'role', label: 'سمت|Role', required: true, list: true },
      { key: 'department', label: 'بخش|Department', list: true },
      { key: 'phone', label: 'تلفن|Phone', list: true, search: true },
      { key: 'salary', label: 'معاش پایه|Base salary', type: 'number' as const, money: true, list: true },
      { key: 'hireDate', label: 'تاریخ استخدام|Hire date', type: 'date' as const, list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'holding', label: 'مرخصی|On leave' },
        { value: 'inactive', label: 'قطع همکاری|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.employees,
  },

  payroll: {
    title: 'معاشات',
    description: 'محاسبه و پرداخت معاش ماهانه',
    entityName: 'فیش معاش|Payslip',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'شماره فیش', required: true, list: true, search: true },
      { key: 'month', label: 'ماه', required: true, list: true, search: true },
      { key: 'employee', label: 'کارمند|Employee', required: true, list: true, search: true },
      { key: 'baseSalary', label: 'پایه', type: 'number' as const, money: true, list: true },
      { key: 'allowance', label: 'مزایا', type: 'number' as const, money: true, list: true },
      { key: 'deduction', label: 'کسورات', type: 'number' as const, money: true, list: true },
      { key: 'net', label: 'خالص', type: 'number' as const, money: true, list: true },
      companyField(),
      statusField([
        { value: 'draft', label: 'پیش‌نویس|Draft' },
        { value: 'approved', label: 'تأیید' },
        { value: 'paid', label: 'پرداخت‌شده|Paid' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.payroll,
  },

  attendance: {
    title: 'حضور و غیاب',
    description: 'ثبت حضور روزانه پرسنل',
    entityName: 'حضور|Attendance',
    statusMap: docStatus,
    fields: [
      { key: 'date', label: 'تاریخ|Date', type: 'date' as const, required: true, list: true, search: true },
      { key: 'employee', label: 'کارمند|Employee', required: true, list: true, search: true },
      { key: 'checkIn', label: 'ورود', list: true },
      { key: 'checkOut', label: 'خروج', list: true },
      { key: 'workHours', label: 'ساعت کار', type: 'number' as const, list: true },
      { key: 'type', label: 'نوع|Type', type: 'select' as const, options: [
        { value: 'present', label: 'حاضر|Present' },
        { value: 'leave', label: 'مرخصی|Leave' },
        { value: 'absent', label: 'غایب|Absent' },
        { value: 'mission', label: 'مأموریت|Mission' },
      ], list: true },
      companyField(),
      statusField([
        { value: 'approved', label: 'تأیید' },
        { value: 'pending', label: 'در انتظار|Pending' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.attendance,
  },

  executiveReport: {
    title: 'گزارش اجرایی',
    description: 'خلاصه شاخص‌های کلیدی مدیریتی',
    entityName: 'شاخص|KPI',
    statusMap: docStatus,
    fields: [
      { key: 'kpi', label: 'شاخص|KPI', required: true, list: true, search: true },
      { key: 'period', label: 'دوره', required: true, list: true },
      { key: 'value', label: 'مقدار|Quantity', type: 'number' as const, money: true, list: true },
      { key: 'unit', label: 'واحد', list: true },
      { key: 'changePct', label: 'تغییر٪', type: 'number' as const, list: true },
      { key: 'owner', label: 'مسئول', list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'به‌روز' },
        { value: 'pending', label: 'نیاز به بررسی' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.executiveReport,
  },

  aging: {
    title: 'سررسید بدهی‌ها',
    description: 'تحلیل سنی مطالبات و بدهی‌ها',
    entityName: 'ردیف سررسید|Aging row',
    statusMap: docStatus,
    fields: [
      { key: 'party', label: 'طرف حساب', required: true, list: true, search: true },
      { key: 'type', label: 'نوع', type: 'select' as const, options: [
        { value: 'receivable', label: 'دریافتنی' },
        { value: 'payable', label: 'پرداختنی' },
      ], list: true },
      { key: 'current', label: 'جاری', type: 'number' as const, money: true, list: true },
      { key: 'd1_30', label: '۱–۳۰ روز', type: 'number' as const, money: true, list: true },
      { key: 'd31_60', label: '۳۱–۶۰ روز', type: 'number' as const, money: true, list: true },
      { key: 'd61_90', label: '۶۱–۹۰ روز', type: 'number' as const, money: true, list: true },
      { key: 'over90', label: 'بیش از ۹۰', type: 'number' as const, money: true, list: true },
      { key: 'total', label: 'جمع', type: 'number' as const, money: true, list: true },
      companyField(),
      statusField([
        { value: 'open', label: 'باز|Open' },
        { value: 'overdue', label: 'بحرانی' },
        { value: 'paid', label: 'تسویه' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.aging,
  },

  companies: {
    title: 'مدیریت شرکت‌ها',
    description: 'شرکت‌های فعال در سیستم چندشرکتی',
    entityName: 'شرکت|Company',
    statusMap: docStatus,
    showCompanySwitcher: false,
    fields: [
      { key: 'code', label: 'کد|Code', required: true, list: true, search: true },
      { key: 'name', label: 'نام|Name', required: true, list: true, search: true },
      { key: 'nameEn', label: 'نام انگلیسی', list: true },
      { key: 'taxId', label: 'شناسه مالیاتی', list: true },
      { key: 'phone', label: 'تلفن|Phone', list: true },
      { key: 'address', label: 'آدرس', list: false, search: true },
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.companies,
  },

  branches: {
    title: 'شعب و دفاتر',
    description: 'شعب عملیاتی هر شرکت',
    entityName: 'شعبه|Branch',
    statusMap: docStatus,
    fields: [
      { key: 'code', label: 'کد شعبه', required: true, list: true, search: true },
      { key: 'name', label: 'نام|Name', required: true, list: true, search: true },
      { key: 'city', label: 'شهر', required: true, list: true },
      { key: 'manager', label: 'مدیر شعبه', list: true },
      { key: 'phone', label: 'تلفن|Phone', list: true },
      companyField(),
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.branches,
  },

  settingsProducts: {
    title: 'مدیریت کالاها',
    description: 'کاتالوگ کالاها و واحد سنجش',
    entityName: 'کالا|Product',
    statusMap: docStatus,
    showCompanySwitcher: false,
    fields: [
      { key: 'code', label: 'کد کالا', required: true, list: true, search: true },
      { key: 'name', label: 'نام|Name', required: true, list: true, search: true },
      { key: 'nameEn', label: 'نام انگلیسی', list: true },
      { key: 'category', label: 'دسته', type: 'select' as const, options: [
        { value: 'fuel', label: 'سوخت' },
        { value: 'oil', label: 'روغن' },
        { value: 'other', label: 'سایر' },
      ], list: true },
      { key: 'unit', label: 'واحد', list: true },
      { key: 'stdPrice', label: 'قیمت پایه', type: 'number' as const, money: true, list: true },
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.settingsProducts,
  },

  users: {
    title: 'کاربران|Users',
    description: 'مدیریت کاربران و نقش دسترسی',
    entityName: 'کاربر|User',
    statusMap: docStatus,
    showCompanySwitcher: false,
    fields: [
      { key: 'email', label: 'ایمیل|Email', required: true, list: true, search: true },
      { key: 'fullName', label: 'نام کامل|Full name', required: true, list: true, search: true },
      { key: 'phone', label: 'تلفن|Phone', list: true },
      {
        key: 'role',
        label: 'نقش|Role',
        type: 'select' as const,
        options: [
          { value: 'admin', label: 'مدیر سیستم|Admin' },
          { value: 'manager', label: 'مدیر عملیات|Manager' },
          { value: 'accountant', label: 'حسابدار|Accountant' },
          { value: 'warehouse', label: 'انباردار|Warehouse' },
          { value: 'sales', label: 'فروش|Sales' },
          { value: 'user', label: 'کاربر|User' },
        ],
        required: true,
        list: true,
      },
      {
        key: 'companyAccess',
        label: 'دسترسی شرکت|Company access',
        type: 'select' as const,
        options: [
          { value: 'arya', label: 'فقط آزیا آریا لمتید|Azya Aria LTD only' },
          { value: 'turkmen', label: 'فقط ترکمن پطرولیم|Turkmen Petroleum only' },
          { value: 'both', label: 'آزیا آریا لمتید و ترکمن پطرولیم (سوئیچ)|Azya Aria LTD & Turkmen Petroleum (switch)' },
        ],
        required: true,
        list: true,
      },
      { key: 'lastLogin', label: 'آخرین ورود|Last login', list: true },
      statusField([
        { value: 'active', label: 'فعال|Active' },
        { value: 'inactive', label: 'غیرفعال|Inactive' },
      ]),
      notesField(),
    ],
    initialRows: demoRows.users,
  },
} satisfies Record<string, CrudModuleConfig>;

export type ModuleKey = keyof typeof modules;
