import type { CrudRow } from '@/components/shared/crud-page';

const empty: CrudRow[] = [];

export const demoRows = {
  purchaseOrders: empty,
  purchaseInvoices: empty,
  purchaseReturns: empty,
  salesOrders: empty,
  salesInvoices: empty,
  salesDeliveries: empty,
  salesReturns: empty,
  warehouseTransfers: empty,
  tanks: empty,
  stocktakes: empty,
  transit: empty,
  wagons: empty,
  trucks: empty,
  drivers: empty,
  transportCompanies: empty,
  customs: empty,
  receivables: empty,
  payables: empty,
  banks: empty,
  cashAccounts: empty,
  ledgerAccounts: empty,
  journalVouchers: empty,
  expenses: empty,
  currencies: empty,
  fxRates: empty,
  employees: empty,
  payroll: empty,
  attendance: empty,
  executiveReport: empty,
  aging: empty,
  companies: empty,
  branches: empty,
  settingsProducts: empty,
  users: empty,
} satisfies Record<string, CrudRow[]>;
