import type { CrudRow } from '@/components/shared/crud-page';
import { seedLedgerRows } from '@/lib/chart-accounts';

const empty: CrudRow[] = [];

export const demoRows = {
  purchaseOrders: empty,
  purchaseInvoices: empty,
  purchaseReturns: empty,
  salesOrders: empty,
  salesInvoices: empty,
  salesDeliveries: empty,
  salesReturns: empty,
  warehouseTransfers: empty,
  tanks: empty,
  stocktakes: empty,
  transit: empty,
  wagons: empty,
  trucks: empty,
  drivers: empty,
  transportCompanies: empty,
  customs: empty,
  receivables: empty,
  payables: empty,
  banks: empty,
  cashAccounts: empty,
  ledgerAccounts: seedLedgerRows('arya') as unknown as CrudRow[],
  journalVouchers: empty,
  expenses: empty,
  currencies: empty,
  fxRates: empty,
  employees: empty,
  payroll: empty,
  attendance: empty,
  executiveReport: empty,
  aging: empty,
  companies: empty,
  branches: empty,
  settingsProducts: empty,
  users: [
    {
      id: 1,
      email: 'turkman',
      fullName: 'System Admin',
      phone: '',
      role: 'admin',
      companyAccess: 'both',
      lastLogin: '2026-08-24',
      status: 'active',
      notes: '',
    },
    {
      id: 2,
      email: 'arya.manager',
      fullName: 'Arya Operations Manager',
      phone: '',
      role: 'manager',
      companyAccess: 'arya',
      lastLogin: '2026-08-23',
      status: 'active',
      notes: '',
    },
    {
      id: 3,
      email: 'turkmen.accountant',
      fullName: 'Turkmen Accountant',
      phone: '',
      role: 'accountant',
      companyAccess: 'turkmen',
      lastLogin: '2026-08-22',
      status: 'active',
      notes: '',
    },
    {
      id: 4,
      email: 'warehouse.ops',
      fullName: 'Warehouse Keeper',
      phone: '',
      role: 'warehouse',
      companyAccess: 'turkmen',
      lastLogin: '2026-08-20',
      status: 'active',
      notes: '',
    },
    {
      id: 5,
      email: 'sales.arya',
      fullName: 'Arya Sales',
      phone: '',
      role: 'sales',
      companyAccess: 'arya',
      lastLogin: '2026-08-21',
      status: 'active',
      notes: '',
    },
  ],
} satisfies Record<string, CrudRow[]>;
